services:

  poste:
    image: analogic/poste.io
    restart: always
    network_mode: host
    volumes:
      - ./mail-data:/data
    environment:
      - HTTPS=ON
      - TZ=America/Argentina/Buenos_Aires
      - h=mail.ejemplo.com.ar # Direcci√≥n del servidor de mail hosting
      #- HTTP_PORT=7080
      #- HTTPS_PORT=7443
      - DISABLE_CLAMAV=FALSE  # TRUE antivirus
      - DISABLE_RSPAMD=FALSE  # TRUE antispam
      - DISABLE_ROUNDCUBE=FALSE  # TRUE
